

default: &default
  adapter: postgresql
  host: localhost
  user: db_user
  password: db_user
  pool: 5
  timeout: 5000

development:
  <<: *default
  #  database: develop_beirholm
  #  database: develop_beirholm2
  database: attendance
